[project]
name = "raydl"
version = "0.0.9"
description = "The library of utilities to help you deal with the deep learning in PyTorch."
readme = "README.md"
authors = [{ name = "Ray Wang" }]
license = { file = "LICENSE" }
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
]
keywords = [
    "PyTorch", "torch", "deep learning", "machine learning",
    "ml", "neural network"
]
dependencies = [
    "torch",
]
requires-python = ">=3.9"

[project.optional-dependencies]
dev = ["black", "ruff", "isort", "pytest"]

[project.urls]
Homepage = "https://github.com/budui/raydl"


[build-system]
requires      = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 119
target-version = ['py39']
include = '\.pyi?$'
# 'extend-exclude' excludes files or directories in addition to the defaults
extend-exclude = '''
# A regex preceded with ^/ will apply only to files and directories
# in the root of the project.
(
  ^/foo.py    # exclude a file named foo.py in the root of the project
  | .*_pb2.py  # exclude autogenerated Protocol Buffer files anywhere in the project
)
'''

[tool.isort]
profile = "black"

[tool.ruff]
select = ["E", "F", "W", "C90", "I", "UP", "B", "C4", "RET", "RUF", "SIM" ]
ignore = ["UP007", "C408", "B905"]
line-length=119

[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"]

[tool.bumpver]
current_version = "0.0.9"
version_pattern = "MAJOR.MINOR.PATCH"
commit_message = "bump version {old_version} -> {new_version}"
commit = true
tag = true
push = false

[tool.bumpver.file_patterns]
"pyproject.toml" = [
    'current_version = "{version}"',
    'version = "{version}"',
]
"src/raydl/__init__.py" = ["{version}"]
